function getStationName(stationCode) {
  const stationNames = {
    HW: "Haridwar Junction (HW)",
    LKO: "Lucknow Junction (LKO)",
    BSB: "Varanasi Junction (BSB)",
    PNBE: "Patna Junction (PNBE)",
    GKP: "Gorakhpur Junction (GKP)",
    JAT: "Jammu Tawi (JAT)",
    JHS: "Jhansi Junction (JHS)",
    NDLS: "New Delhi (NDLS)",
    BCT: "Mumbai (BCT)",
    CSMT: "Mumbai Chhatrapati Shivaji Maharaj Terminus (CSMT)",
    BZA: "Vijayawada Junction (BZA)",
    VSKP: "Visakhapatnam Junction (VSKP)",
    MAS: "Chennai Central (MAS)",
    KGP: "Kharagpur Junction (KGP)",
    KZJ: "Kazipet Junction (KZJ)",
    SBC: "Bengaluru City Junction (SBC)",
    RK: "Roorkee (RK)",
    BPL: "Bhopal Junction (BPL)",
    JBP: "Jabalpur Junction (JBP)",
    MOZ: "Muzaffarnagar (MOZ)",
    KOTA: "Kota Junction (KOTA)",
    BRC: "Vadodara Junction (BRC)",
    ABU: "Station Code Index (ABU)",
    ABR: "Road (ABR)",
    ANVT: "Anand Vihar Terminal (ANVT)",
    ASR: "Amritsar Junction (ASR)",
    IL: "Indore Junction (IL)",
    ADB: "Adilabad (ADB)",
    AD: "Adoni (AD)",
    AII: "Ajmer Junction (AII)",
    ALD: "Allahabad Junction (ALD)",
    ADRA: "Adra (ADRA)",
    FORT: "Agra (FORT)",
    AGRA: "Af (AGRA)",
    AGC: "Cantt. (AGC)",
    ANG: "L (ANG)",
    ADI: "Ahmedabad (ADI)",
    AII: "Ajmer (AII)",
    GARH: "Li (GARH)",
    ALD: "Allahabad (ALD)",
    AWY: "Uva (AWY)",
    AWR: "War (AWR)",
    AN: "Ner (AN)",
    AADR: "Amb Andavra (AADR)",
    UMB: "A Cantt. (UMB)",
    ABKP: "Kapur (ABKP)",
    LA: "Am (LA)",
    ASR: "Amritsar (ASR)",
    LL: "Ne (LL)",
    ANAND: "Annd (ANAND)",
    ANDN: "Nagar (ANDN)",
    ATP: "Anantapur (ATP)",
    ANV: "Annavaram (ANV)",
    APR: "Anuppur (APR)",
    ARA: "Ara (ARA)",
    AR: "Is (AR)",
    KERE: "Si (KERE)",
    AWB: "Aurangabad (AWB)",
    AY: "Ayodhya (AY)",
    AMH: "Azamgarh (AMH)",
    BPB: "Badarpur (BPB)",
    BAGA: "Bd (BAGA)",
    ROAD: "Ar (ROAD)",
    BA: "Brwd (BA)",
    BDME: "Dyanathdham (BDME)",
    BTC: "Aghat (BTC)",
    BALU: "Gaon (BALU)",
    BPQ: "Hah (BPQ)",
    LLI: "Tadepa (LLI)",
    BNQ: "Banarhat (BNQ)",
    BANDE: "Bnda (BANDE)",
    BAND: "Bdc (BAND)",
    DRA: "Ban (DRA)",
    CITY: "Udaipur (CITY)",
    CANTT: "Tapur (CANTT)",
    BW: "Bangarapet (BW)",
    SI: "Tenka (SI)",
    BQA: "Bankura (BQA)",
    BNK: "I (BNK)",
    BAR: "Bbk (BAR)",
    BBN: "Il (BBN)",
    BAZ: "Baran (BAZ)",
    BTU: "Baraut (BTU)",
    BARE: "Rae (BARE)",
    BARHN: "Brga (BARHN)",
    BNY: "I (BNY)",
    BRKA: "Barkakana (BRKA)",
    BME: "Barmer (BME)",
    BOF: "Barog (BOF)",
    BOE: "I (BOE)",
    HI: "Bat (HI)",
    BXN: "Bayana (BXN)",
    BEA: "S (BEA)",
    BER: "Beawar (BER)",
    BAP: "Apur (BAP)",
    BGM: "Gaum (BGM)",
    BETT: "B Ay (BETT)",
    BTH: "Ah (BTH)",
    BZU: "L (BZU)",
    BOY: "I (BOY)",
    BHC: "Bhadrak (BHC)",
    BGP: "Bhagalpur (BGP)",
    KI: "Hagat (KI)",
    BTE: "Bharatpur (BTE)",
    BH: "Ili (BH)",
    BYT: "Bhatapara (BYT)",
    BT: "L (BT)",
    BHATN: "Jl (BHATN)",
    BTT: "I (BTT)",
    BWP: "Patna (BWP)",
    TOWN: "Puram (TOWN)",
    BNW: "I (BNW)",
    BP: "Bhopal (BP)",
    BB: "Bhubaneswar (BB)",
    BHUJ: "Bhuj (BHUJ)",
    BSL: "Bhusaval (BSL)",
    APUR: "Ij (APUR)",
    NOR: "Ij (NOR)",
    BKN: "Bikaner (BKN)",
    BNV: "I (BNV)",
    RRB: "Rur (RRB)",
    BTTR: "Tragunta (BTTR)",
    RA: "Yavara (RA)",
    BRRG: "Garh (BRRG)",
    ILI: "Mach (ILI)",
    BGBR: "Baghbahar (BGBR)",
    STEEL: "Bokaro (STEEL)",
    BKSC: "City (BKSC)",
    BOR: "N Bhp (BOR)",
    LI: "Ve (LI)",
    BTD: "Botad (BTD)",
    BEM: "Budaun (BEM)",
    BAU: "Burhanpur (BAU)",
    BUXAR: "Buw (BUXAR)",
    CNO: "Canacona (CNO)",
    CHAKK: "Caa (CHAKK)",
    CHKB: "Bank (CHKB)",
    CKP: "Chakradharpur (CKP)",
    LIS: "Cha (LIS)",
    CPH: "Champa (CPH)",
    CNA: "Ya (CNA)",
    CDG: "Chandigarh (CDG)",
    CD: "Chandrapur (CD)",
    CRP: "Chandrapura (CRP)",
    CPK: "Chaparmukh (CPK)",
    CAP: "Hatrapur (CAP)",
    CNGR: "Chengannur (CNGR)",
    MS: "Chennai Egmore (MS)",
    CPR: "Chhapra (CPR)",
    CWA: "Ndwara (CWA)",
    CDM: "Dambaram (CDM)",
    CH: "C K T D (CH)",
    KARV: "Trakootdham (KARV)",
    CR: "An (CR)",
    COR: "Ttaurgarh (COR)",
    CTO: "Ttoor (CTO)",
    CPU: "Chopan (CPU)",
    CAR: "Chunar (CAR)",
    CUR: "Churu (CUR)",
    ONR: "Coonoor (ONR)",
    PORT: "Kakinada (PORT)",
    HX: "Cuddapah (HX)",
    CTC: "Cuttack (CTC)",
    DR: "Dadar (DR)",
    DAHOD: "Drd (DAHOD)",
    DA: "Dhd (DA)",
    DTO: "J (DTO)",
    DRZ: "Hara (DRZ)",
    DMO: "Damoh (DMO)",
    DNR: "Danapur (DNR)",
    DBG: "Darbhanga (DBG)",
    DD: "Daund (DD)",
    DVG: "Davangere (DVG)",
    DDN: "Dehradun (DDN)",
    DO: "One (DO)",
    DLI: "Delhi (DLI)",
    DELHI: "New (DELHI)",
    DE: "Ndls (DE)",
    DEC: "Cantt. (DEC)",
    SARAI: "Delhi (SARAI)",
    DEE: "Rohilla (DEE)",
    DEO: "Adar (DEO)",
    DV: "Li (DV)",
    DMN: "Dhamangaon (DMN)",
    DHN: "Dhanbad (DHN)",
    DAB: "Dharmabad (DAB)",
    DMR: "Dharmanagar (DMR)",
    DP: "I (DP)",
    DMM: "Dharmavaram (DMM)",
    DWR: "Dharwad (DWR)",
    DHO: "Pur (DHO)",
    DHONE: "Lj (DHONE)",
    DHG: "Dhrangadhra (DHG)",
    DHUR: "Dbb (DHUR)",
    DU: "I (DU)",
    DBRG: "Dibrugarh (DBRG)",
    DMV: "Mapur (DMV)",
    DGG: "Dongargarh (DGG)",
    DK: "L (DK)",
    DNRP: "Dungarpur (DNRP)",
    DURG: "Durg (DURG)",
    DGR: "Durgapur (DGR)",
    DVD: "Duvvada (DVD)",
    DWK: "Dwarka (DWK)",
    EE: "Uru (EE)",
    ERODE: "Ern (ERODE)",
    ETW: "Etawah (ETW)",
    FD: "Zabad (FD)",
    FDB: "Dabad (FDB)",
    FBD: "Farrukhabad (FBD)",
    CHAND: "Abad (CHAND)",
    FTP: "Fatehpur (FTP)",
    FUT: "Fatuha (FUT)",
    FKA: "Ka (FKA)",
    FZD: "Rozabad (FZD)",
    FORBE: "Fzr (FORBE)",
    FBG: "J (FBG)",
    FKG: "Ng (FKG)",
    GDG: "Gadag (GDG)",
    GIM: "Gandhidham (GIM)",
    GAD: "Road (GAD)",
    GGC: "Ty (GGC)",
    GEVRA: "G Aya (GEVRA)",
    SIL: "Ghat (SIL)",
    GZB: "Abad (GZB)",
    GDA: "Godhra (GDA)",
    GK: "A Gokarannath (GK)",
    GD: "Gonda (GD)",
    GY: "Gooty (GY)",
    ON: "Unnao (ON)",
    GOGH: "Hat (GOGH)",
    GDV: "Vada (GDV)",
    GDR: "Gudur (GDR)",
    GR: "Li S (GR)",
    GUNA: "Guna (GUNA)",
    GT: "L (GT)",
    GNT: "Guntur (GNT)",
    GU: "I S (GU)",
    UR: "Ruvay (UR)",
    GHY: "Guwahati (GHY)",
    GWL: "Gwalior (GWL)",
    HBJ: "Habibganj (HBJ)",
    HJP: "Hajipur (HJP)",
    HDB: "I (HDB)",
    HO: "J (HO)",
    HMH: "Hanumangarh (HMH)",
    HAPA: "Hapa (HAPA)",
    HPU: "Hapur (HPU)",
    HD: "Harda (HD)",
    HRR: "Har (HRR)",
    HPP: "Pur (HPP)",
    HTE: "Hatia (HTE)",
    NED: "B Nanded (NED)",
    NAGAR: "Urendra (NAGAR)",
    HUP: "Ndupur (HUP)",
    HBD: "Hangabad (HBD)",
    HPT: "Pet (HPT)",
    HOWBA: "Ra (HOWBA)",
    HWH: "Howrah (HWH)",
    UBL: "Hubli (UBL)",
    HYB: "Hyderabad (HYB)",
    GP: "I I (GP)",
    INDB: "Indore (INDB)",
    AMPUR: "Isl (AMPUR)",
    ET: "Itarsi (ET)",
    JDB: "Agdalpur (JDB)",
    JP: "Jaipur (JP)",
    JYP: "Aypur (JYP)",
    JSM: "Jaisalmer (JSM)",
    KEON: "Pur (KEON)",
    KR: "Si (KR)",
    JL: "Ar (JL)",
    IJ: "Arpetta (IJ)",
    JAMMU: "Mp (JAMMU)",
    JAM: "Jamnagar (JAM)",
    NH: "I J (NH)",
    ME: "Js (ME)",
    JYG: "Jaynagar (JYG)",
    LS: "Va (LS)",
    JS: "Uguda (JS)",
    ND: "L (ND)",
    JU: "Jodhpur (JU)",
    KCG: "Kacheguda (KCG)",
    KA: "Ll (KA)",
    KCF: "I (KCF)",
    KYN: "Yan (KYN)",
    KYQ: "Kamakhya (KYQ)",
    CAPE: "Kanniyakumari (CAPE)",
    CAN: "Kannur (CAN)",
    CNB: "Kanpur Central (CNB)",
    CPA: "J (CPA)",
    CP: "J (CP)",
    MGAN: "Kari (MGAN)",
    KUN: "L (KUN)",
    KRR: "Karur (KRR)",
    KAWR: "Karwar (KAWR)",
    KGQ: "God (KGQ)",
    KGM: "Kathgodam (KGM)",
    KIR: "Katihar (KIR)",
    KTE: "I (KTE)",
    KMZ: "Murwara (KMZ)",
    KPD: "I (KPD)",
    KWAE: "Katwa (KWAE)",
    KZ: "Pet (KZ)",
    NGA: "Si (NGA)",
    KENDU: "Ng (KENDU)",
    KD: "Hargarh (KD)",
    KHA: "Kgg (KHA)",
    ABAD: "Lil (ABAD)",
    KMT: "Khammam (KMT)",
    KNW: "Khandwa (KNW)",
    KEX: "Khekra (KEX)",
    KHUR: "Kur (KHUR)",
    KNE: "Kishanganj (KNE)",
    KCVL: "Kochuveli (KCVL)",
    KQN: "Road (KQN)",
    KOAA: "Kolkata (KOAA)",
    KPG: "Kopergaon (KPG)",
    KRPU: "Koraput (KRPU)",
    KRBA: "Korba (KRBA)",
    KTW: "Kotdwara (KTW)",
    KKP: "Kot Kapura (KKP)",
    KTYM: "Kottayam (KTYM)",
    IS: "Hr (IS)",
    KN: "Ty (KN)",
    KUGT: "Kumarghat (KUGT)",
    KMU: "Kumbakonam (KMU)",
    KUDA: "Kundapura (KUDA)",
    KRNT: "Town (KRNT)",
    KKDE: "Hetra (KKDE)",
    TPUR: "Li (TPUR)",
    TILAK: "Lokmanya (TILAK)",
    HA: "Is (HA)",
    LJN: "Lucknow (LJN)",
    UN: "I L (UN)",
    MTM: "Patnam (MTM)",
    MDT: "Hat (MDT)",
    MAD: "Maddur (MAD)",
    MAO: "Madgaon (Goa) (MAO)",
    MB: "Moradabad (MB)",
    MDP: "Madhupur (MDP)",
    MAHA: "Mdu (MAHA)",
    MBNR: "Mahbubnagar (MBNR)",
    UVA: "Mah (UVA)",
    MUN: "Mhv (MUN)",
    MNGD: "Guda (MNGD)",
    MBA: "Mahoba (MBA)",
    MALDA: "Mkc (MALDA)",
    MLDT: "Town (MLDT)",
    MNM: "I (MNM)",
    MUV: "Manduadih (MUV)",
    MAQ: "Mangalore Central (MAQ)",
    JN: "Mangalore (JN)",
    MAN: "Mq (MAN)",
    MKP: "Kpur (MKP)",
    MUR: "I (MUR)",
    MMR: "Manmad (MMR)",
    MNE: "Si (MNE)",
    MANU: "Manu (MANU)",
    MXN: "I (MXN)",
    MTJ: "Mathura (MTJ)",
    MAU: "Mau (MAU)",
    MTC: "Ty (MTC)",
    MTP: "Mettupalayam (MTP)",
    ORE: "Dnap (ORE)",
    MR: "J (MR)",
    MRGA: "Aguda (MRGA)",
    MZP: "Rzapur (MZP)",
    MOF: "Moga (MOF)",
    MKA: "Mokama (MKA)",
    PDKT: "I (PDKT)",
    PP: "Ya (PP)",
    PURI: "Puri (PURI)",
    PAU: "Purna (PAU)",
    PURU: "Prna (PURU)",
    RADH: "Prr (RADH)",
    RDP: "Kapur (RDP)",
    RB: "Li (RB)",
    RC: "Chur (RC)",
    RKM: "Raja Ki Mandi (RKM)",
    RJQ: "Rajendranagar (RJQ)",
    RJT: "Rajkot (RJT)",
    RP: "Pura (RP)",
    RDM: "Ramagundam (RDM)",
    RMD: "Ramanathapuram (RMD)",
    RMM: "Rameswaram (RMM)",
    RMR: "Ramnagar (RMR)",
    RMU: "N. (RMU)",
    RPH: "Rampurhat (RPH)",
    RHA: "Ranaghat (RHA)",
    RNC: "Ranchi (RNC)",
    NORTH: "Rangapara (NORTH)",
    RANG: "Rpan (RANG)",
    RNY: "Ya (RNY)",
    RO: "Nagar (RO)",
    RTGH: "Ratangarh (RTGH)",
    RTM: "Am (RTM)",
    RN: "I (RN)",
    RXL: "Raxaul (RXL)",
    RGDA: "Rayagada (RGDA)",
    RU: "Gunta (RU)",
    REWA: "Rewa (REWA)",
    RE: "I (RE)",
    RG: "S (RG)",
    ROK: "Rohtak (ROK)",
    SL: "Tanpur (SL)",
    SPJ: "Samastipur (SPJ)",
    SDAH: "Sealdah (SDAH)",
    SC: "Secunderabad (SC)",
    SML: "Shimla (SML)",
    VP: "I S (VP)",
    HOR: "Si (HOR)",
    KAR: "Si (KAR)",
    MK: "I (MK)",
    MUE: "Mudkhed (MUE)",
    MGS: "Mughalsarai (MGS)",
    CST: "Mumbai (CST)",
    MZ: "Ek (MZ)",
    MZR: "Apur (MZR)",
    MFP: "Muzaffarpur (MFP)",
    MYS: "Mysore (MYS)",
    NDAE: "Pdham (NDAE)",
    NDKD: "Kudi (NDKD)",
    NAGBH: "Sl (NAGBH)",
    NAGDA: "Nab (NAGDA)",
    NCR: "Nagore (NCR)",
    NGP: "Nagpur (NGP)",
    NA: "Nagrakatankb (NA)",
    JI: "Na (JI)",
    NBD: "Babad (NBD)",
    NRE: "Ur (NRE)",
    NGN: "Nandgaon (NGN)",
    NDB: "Nandurbar (NDB)",
    NKE: "J (NKE)",
    NU: "Ngpur (NU)",
    NRW: "Narwana (NRW)",
    NK: "K Road (NK)",
    NUH: "Naugarh (NUH)",
    BO: "Chandra (BO)",
    GMO: "Gomoh (GMO)",
    NOQ: "Purduar (NOQ)",
    BONGA: "New (BONGA)",
    NBQ: "Gaon (NBQ)",
    NCB: "New Coochbehar (NCB)",
    NEW: "Nmz (NEW)",
    NFK: "Farakka (NFK)",
    NJP: "New Jalpaiguri (NJP)",
    NT: "A (NT)",
    NI: "Ndd (NI)",
    NM: "Am (NM)",
    NMH: "Mach (NMH)",
    NZB: "Nizamabad (NZB)",
    NZM: "Nizamuddin (NZM)",
    ODB: "Odlabari (ODB)",
    OKHA: "Okha (OKHA)",
    ORA: "I (ORA)",
    PC: "Pachora (PC)",
    PNU: "Anpur (PNU)",
    PGT: "Lakkad (PGT)",
    PA: "Pgtn (PA)",
    AKA: "Li (AKA)",
    PVR: "Pandharapur (PVR)",
    PNP: "Pat (PNP)",
    PRDP: "Aradeep (PRDP)",
    PNME: "Nath (PNME)",
    PNV: "L (PNV)",
    PTK: "Pathankot (PTK)",
    PATNA: "Pnbe (PATNA)",
    PHA: "Pnc (PHA)",
    PFM: "Phaphamau (PFM)",
    PT: "Podanur (PT)",
    PBR: "Porbandar (PBR)",
    PBH: "Pratapgarh (PBH)",
    PDY: "Uducherry (PDY)",
    CHAR: "Sil (CHAR)",
    GHAT: "Sil (GHAT)",
    SILI: "Htt (SILI)",
    ST: "Surat (ST)",
    GUR: "Lu (GUR)",
    MA: "Si (MA)",
    NGRAU: "Si (NGRAU)",
    RPUR: "Si (RPUR)",
    WA: "Sis (WA)",
    TAPUR: "Si (TAPUR)",
    WAN: "Si (WAN)",
    SRI: "Ee (SRI)",
    SHAHU: "Chhatrapati (SHAHU)",
    AYAM: "Il (AYAM)",
    PN: "Ss (PN)",
    TDD: "Gudem (TDD)",
    TBM: "Tambaram (TBM)",
    TATA: "Tata N A G A R (TATA)",
    ERY: "Ss (ERY)",
    TZTB: "Tezpur (TZTB)",
    TJ: "Thanjavur (TJ)",
    TVR: "Ruvarur. (TVR)",
    TCN: "Ruchendur (TCN)",
    TPTY: "Tirupati (TPTY)",
    TUP: "Ruppur (TUP)",
    TCR: "Ur (TCR)",
    TVC: "Hiruvananthapuram (TVC)",
    TUM: "Tnm (TUM)",
    TUND: "Tmr (TUND)",
    TUN: "I (TUN)",
    TN: "Tuticorin (TN)",
    UHP: "Udhampur (UHP)",
    UDN: "Udhna (UDN)",
    UD: "I (UD)",
    UNA: "Una (UNA)",
    UCR: "Unchahar (UCR)",
    BD: "Vadakara (BD)",
    BSB: "Varanasi (BSB)",
    VA: "Vak (VA)",
    VSG: "Vasco-Da-Gama (VSG)",
    VRL: "Veraval (VRL)",
    VG: "Ramgam (VG)",
    VPT: "N. (VPT)",
    VZM: "Anagaram (VZM)",
    WAD: "I (WAD)",
    WKR: "Wankaner (WKR)",
    YPR: "Yesvantpur (YPR)",
    ZBD: "Zafarabad (ZBD)",
  };
  return stationNames[stationCode] || stationCode;
}
